# Copyright (c) 2018-2020 by Antoine Doucet, All Rights Reserved.
# Copyright (c) 1994-2020 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/133
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 133\#.scm
MODULES_SCM = 133.scm 133.sld test.scm
MAIN_MODULES = 133
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
